name: Pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: npm test

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  supertest:
    name: Supertest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run supertest
        run: npm run supertest

  deploy-test:
    name: Deploy to Test Server
    needs: [unit-tests, linting, supertest]
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment message
        run: |
        echo "now deploying branch: ${{ github.ref }} to the test server"

  deploy-production:
    name: Deploy to Production
    needs: [unit-tests, linting, supertest]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print deployment message
        run: echo "now deploying to production"
